package com.litian.domain;

public class Config {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_p2p_conf.InstCode
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    private String InstCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_p2p_conf.MerchCode
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    private String MerchCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_p2p_conf.MerchName
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    private String MerchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_p2p_conf.CardBin
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    private String CardBin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_p2p_conf.ErInstCode
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    private String ErInstCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_p2p_conf.ErIssuer
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    private String ErIssuer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_p2p_conf.ErProduct
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    private String ErProduct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_p2p_conf.ErSource
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    private String ErSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_p2p_conf.ErType
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    private String ErType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_p2p_conf.FileKey
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    private String FileKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_p2p_conf.RedAccount
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    private String RedAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_p2p_conf.ChargeAccount
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    private String ChargeAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_p2p_conf.Version
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    private String Version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_p2p_conf.InstCode
     *
     * @return the value of dt_p2p_conf.InstCode
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public String getInstCode() {
        return InstCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_p2p_conf.InstCode
     *
     * @param InstCode the value for dt_p2p_conf.InstCode
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public void setInstCode(String InstCode) {
        this.InstCode = InstCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_p2p_conf.MerchCode
     *
     * @return the value of dt_p2p_conf.MerchCode
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public String getMerchCode() {
        return MerchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_p2p_conf.MerchCode
     *
     * @param MerchCode the value for dt_p2p_conf.MerchCode
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public void setMerchCode(String MerchCode) {
        this.MerchCode = MerchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_p2p_conf.MerchName
     *
     * @return the value of dt_p2p_conf.MerchName
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public String getMerchName() {
        return MerchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_p2p_conf.MerchName
     *
     * @param MerchName the value for dt_p2p_conf.MerchName
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public void setMerchName(String MerchName) {
        this.MerchName = MerchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_p2p_conf.CardBin
     *
     * @return the value of dt_p2p_conf.CardBin
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public String getCardBin() {
        return CardBin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_p2p_conf.CardBin
     *
     * @param CardBin the value for dt_p2p_conf.CardBin
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public void setCardBin(String CardBin) {
        this.CardBin = CardBin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_p2p_conf.ErInstCode
     *
     * @return the value of dt_p2p_conf.ErInstCode
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public String getErInstCode() {
        return ErInstCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_p2p_conf.ErInstCode
     *
     * @param ErInstCode the value for dt_p2p_conf.ErInstCode
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public void setErInstCode(String ErInstCode) {
        this.ErInstCode = ErInstCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_p2p_conf.ErIssuer
     *
     * @return the value of dt_p2p_conf.ErIssuer
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public String getErIssuer() {
        return ErIssuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_p2p_conf.ErIssuer
     *
     * @param ErIssuer the value for dt_p2p_conf.ErIssuer
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public void setErIssuer(String ErIssuer) {
        this.ErIssuer = ErIssuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_p2p_conf.ErProduct
     *
     * @return the value of dt_p2p_conf.ErProduct
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public String getErProduct() {
        return ErProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_p2p_conf.ErProduct
     *
     * @param ErProduct the value for dt_p2p_conf.ErProduct
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public void setErProduct(String ErProduct) {
        this.ErProduct = ErProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_p2p_conf.ErSource
     *
     * @return the value of dt_p2p_conf.ErSource
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public String getErSource() {
        return ErSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_p2p_conf.ErSource
     *
     * @param ErSource the value for dt_p2p_conf.ErSource
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public void setErSource(String ErSource) {
        this.ErSource = ErSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_p2p_conf.ErType
     *
     * @return the value of dt_p2p_conf.ErType
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public String getErType() {
        return ErType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_p2p_conf.ErType
     *
     * @param ErType the value for dt_p2p_conf.ErType
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public void setErType(String ErType) {
        this.ErType = ErType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_p2p_conf.FileKey
     *
     * @return the value of dt_p2p_conf.FileKey
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public String getFileKey() {
        return FileKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_p2p_conf.FileKey
     *
     * @param FileKey the value for dt_p2p_conf.FileKey
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public void setFileKey(String FileKey) {
        this.FileKey = FileKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_p2p_conf.RedAccount
     *
     * @return the value of dt_p2p_conf.RedAccount
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public String getRedAccount() {
        return RedAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_p2p_conf.RedAccount
     *
     * @param RedAccount the value for dt_p2p_conf.RedAccount
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public void setRedAccount(String RedAccount) {
        this.RedAccount = RedAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_p2p_conf.ChargeAccount
     *
     * @return the value of dt_p2p_conf.ChargeAccount
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public String getChargeAccount() {
        return ChargeAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_p2p_conf.ChargeAccount
     *
     * @param ChargeAccount the value for dt_p2p_conf.ChargeAccount
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public void setChargeAccount(String ChargeAccount) {
        this.ChargeAccount = ChargeAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_p2p_conf.Version
     *
     * @return the value of dt_p2p_conf.Version
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public String getVersion() {
        return Version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_p2p_conf.Version
     *
     * @param Version the value for dt_p2p_conf.Version
     *
     * @mbggenerated Thu Jul 07 14:32:04 CST 2016
     */
    public void setVersion(String Version) {
        this.Version = Version;
    }
}