package com.litian.domain;

public class OperationInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_operation_info.sid
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_operation_info.seq
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_operation_info.txCode
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    private String txCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_operation_info.remark
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_operation_info.onlineOrPage
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    private String onlineOrPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_operation_info.interfaceUrl
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    private String interfaceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_operation_info.pageUrl
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    private String pageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_operation_info.isDel
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    private Integer isdel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_operation_info.flag
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_operation_info.sid
     *
     * @return the value of dt_operation_info.sid
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_operation_info.sid
     *
     * @param sid the value for dt_operation_info.sid
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_operation_info.seq
     *
     * @return the value of dt_operation_info.seq
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_operation_info.seq
     *
     * @param seq the value for dt_operation_info.seq
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_operation_info.txCode
     *
     * @return the value of dt_operation_info.txCode
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    public String getTxCode() {
        return txCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_operation_info.txCode
     *
     * @param txCode the value for dt_operation_info.txCode
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    public void setTxCode(String txCode) {
        this.txCode = txCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_operation_info.remark
     *
     * @return the value of dt_operation_info.remark
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_operation_info.remark
     *
     * @param remark the value for dt_operation_info.remark
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_operation_info.onlineOrPage
     *
     * @return the value of dt_operation_info.onlineOrPage
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    public String getOnlineOrPage() {
        return onlineOrPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_operation_info.onlineOrPage
     *
     * @param onlineOrPage the value for dt_operation_info.onlineOrPage
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    public void setOnlineOrPage(String onlineOrPage) {
        this.onlineOrPage = onlineOrPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_operation_info.interfaceUrl
     *
     * @return the value of dt_operation_info.interfaceUrl
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    public String getInterfaceUrl() {
        return interfaceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_operation_info.interfaceUrl
     *
     * @param interfaceUrl the value for dt_operation_info.interfaceUrl
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    public void setInterfaceUrl(String interfaceUrl) {
        this.interfaceUrl = interfaceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_operation_info.pageUrl
     *
     * @return the value of dt_operation_info.pageUrl
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    public String getPageUrl() {
        return pageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_operation_info.pageUrl
     *
     * @param pageUrl the value for dt_operation_info.pageUrl
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    public void setPageUrl(String pageUrl) {
        this.pageUrl = pageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_operation_info.isDel
     *
     * @return the value of dt_operation_info.isDel
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_operation_info.isDel
     *
     * @param isdel the value for dt_operation_info.isDel
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_operation_info.flag
     *
     * @return the value of dt_operation_info.flag
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_operation_info.flag
     *
     * @param flag the value for dt_operation_info.flag
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}