package com.litian.dao;

import com.litian.domain.OperationInfo;

import java.util.List;

public interface OperationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_operation_info
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_operation_info
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    int insert(OperationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_operation_info
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    int insertSelective(OperationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_operation_info
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    OperationInfo selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_operation_info
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    int updateByPrimaryKeySelective(OperationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_operation_info
     *
     * @mbggenerated Thu Sep 28 16:13:30 CST 2017
     */
    int updateByPrimaryKey(OperationInfo record);
    /**
     * 查询所有的数据信息
     * @return
     */
    List<OperationInfo> findAll();
}